import nodemailer from 'nodemailer';
import dotenv from 'dotenv';
dotenv.config();

// ── Transporter — Dedicated CyberShield Portal Mailer ────────
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.GMAIL_USER,       // omkarraichur0102@gmail.com (SMTP auth)
    pass: process.env.GMAIL_PASS        // App password
  }
});

// Sender displays as official portal address
const SENDER_ADDRESS = process.env.ADMIN_EMAIL || 'noreplyyourcyberportal@gmail.com';
const SENDER_DISPLAY = `CyberShield | Ministry of Home Affairs <${SENDER_ADDRESS}>`;

// ── Severity colour helpers ───────────────────────────────────
function severityColor(severity) {
  const map = {
    Critical: { bg: '#991B1B', text: '#FEE2E2', badge: '#EF4444' },
    High:     { bg: '#92400E', text: '#FEF3C7', badge: '#F59E0B' },
    Medium:   { bg: '#78350F', text: '#FEF9C3', badge: '#EAB308' },
    Low:      { bg: '#14532D', text: '#DCFCE7', badge: '#22C55E' }
  };
  return map[severity] || map.Medium;
}

// ── Shared GOI-style header HTML ─────────────────────────────
function govtHeader(title, subtitle) {
  return `
  <!-- GOI LETTERHEAD -->
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0F172A; border-bottom:3px solid #FF6B00;">
    <tr>
      <td style="padding:0; text-align:center;">
        <!-- TOP TRICOLOR STRIPE -->
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td style="height:5px; background:#FF6B00;"></td>
          </tr>
          <tr>
            <td style="height:5px; background:#FFFFFF;"></td>
          </tr>
          <tr>
            <td style="height:5px; background:#138808;"></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td style="padding:28px 40px 20px; text-align:center;">
        <!-- EMBLEM LINE -->
        <div style="font-size:11px; font-family:'Courier New',monospace; color:#64748B; letter-spacing:3px; text-transform:uppercase; margin-bottom:10px;">
          &#9670; GOVERNMENT OF INDIA &#9670; MINISTRY OF HOME AFFAIRS &#9670;
        </div>
        <!-- TITLE -->
        <div style="font-size:22px; font-weight:900; color:#E2E8F0; font-family:Georgia,serif; letter-spacing:1px; text-transform:uppercase; margin-bottom:4px;">
          CyberShield India
        </div>
        <div style="font-size:11px; color:#94A3B8; font-family:Arial,sans-serif; letter-spacing:2px; text-transform:uppercase; margin-bottom:6px;">
          National Cyber Crime Intelligence Platform
        </div>
        <div style="font-size:10px; color:#475569; font-family:'Courier New',monospace; letter-spacing:1px;">
          Established under IT Act 2000 | BNS 2024 Compliant
        </div>
      </td>
    </tr>
    <!-- HEADER TYPE BANNER -->
    <tr>
      <td style="background:#1E293B; padding:12px 40px; border-top:1px solid rgba(255,255,255,0.07); border-bottom:1px solid rgba(255,255,255,0.07); text-align:center;">
        <span style="font-size:13px; font-weight:700; color:#00D4FF; font-family:'Courier New',monospace; letter-spacing:3px; text-transform:uppercase;">${title}</span>
        ${subtitle ? `<div style="font-size:10px; color:#64748B; margin-top:3px; letter-spacing:1px; text-transform:uppercase;">${subtitle}</div>` : ''}
      </td>
    </tr>
  </table>`;
}

// ── Shared GOI-style footer HTML ─────────────────────────────
function govtFooter(ref_no) {
  return `
  <!-- FOOTER -->
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0F172A; border-top:1px solid rgba(255,255,255,0.08);">
    <tr>
      <td style="padding:20px 40px;">
        <!-- TRICOLOR BOTTOM -->
        <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:16px;">
          <tr>
            <td style="height:2px; background:#FF6B00;"></td>
            <td style="height:2px; background:#FFFFFF;"></td>
            <td style="height:2px; background:#138808;"></td>
          </tr>
        </table>
        <div style="font-size:10px; color:#475569; font-family:'Courier New',monospace; line-height:1.8; text-align:center;">
          <strong style="color:#64748B;">CONFIDENTIALITY NOTICE:</strong> This communication is intended solely for the addressee and is protected under the Information Technology Act, 2000. Unauthorized disclosure, copying, or distribution is strictly prohibited and may result in prosecution under BNS 2024.<br><br>
          REF: ${ref_no || 'N/A'} &nbsp;|&nbsp; AUTO-GENERATED BY CYBERSHIELD AI SYSTEM &nbsp;|&nbsp; DO NOT REPLY TO THIS EMAIL<br>
          CyberShield India &mdash; National Cyber Crime Intelligence Platform &mdash; cybershield.gov.in<br>
          Helpline: <strong style="color:#00D4FF;">1930</strong> (24x7) &nbsp;|&nbsp; Emergency: <strong style="color:#EF4444;">112</strong>
        </div>
      </td>
    </tr>
  </table>`;
}

// ── Welcome / Acknowledgment Email ───────────────────────────
export async function sendWelcomeEmail(to, data) {
  const { ref_no, categories, severity, name } = data;
  const sev = severityColor(severity);

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Complaint Registered — ${ref_no}</title>
</head>
<body style="margin:0; padding:0; background:#0A0F1E; font-family:Arial,'Helvetica Neue',sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0" style="background:#0A0F1E; padding:30px 20px;">
<tr><td align="center">
<table width="620" cellpadding="0" cellspacing="0" style="background:#0D1526; border-radius:4px; overflow:hidden; border:1px solid rgba(255,255,255,0.08); box-shadow:0 0 60px rgba(0,0,0,0.6);">

  <!-- GOVERNMENT HEADER -->
  <tr><td>
    ${govtHeader('E-FIR Acknowledgment Notice', 'Complaint Successfully Registered with National Cyber Cell')}
  </td></tr>

  <!-- ACK NUMBER BANNER -->
  <tr>
    <td style="background:#1E293B; padding:20px 40px; border-bottom:1px solid rgba(255,255,255,0.06);">
      <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td>
            <div style="font-size:10px; color:#64748B; font-family:'Courier New',monospace; letter-spacing:2px; text-transform:uppercase; margin-bottom:6px;">Acknowledgment Reference Number</div>
            <div style="font-size:28px; font-weight:900; color:#00D4FF; font-family:'Courier New',monospace; letter-spacing:6px;">${ref_no}</div>
          </td>
          <td align="right" valign="middle">
            <div style="display:inline-block; background:${sev.bg}; color:${sev.badge}; border:1px solid ${sev.badge}40; padding:6px 16px; border-radius:4px; font-size:11px; font-weight:700; font-family:'Courier New',monospace; letter-spacing:2px; text-transform:uppercase;">
              &#9632; ${severity} PRIORITY
            </div>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <!-- BODY -->
  <tr>
    <td style="padding:32px 40px;">

      <!-- SALUTATION -->
      <p style="font-size:14px; color:#94A3B8; margin:0 0 8px;">To,</p>
      <p style="font-size:16px; font-weight:700; color:#E2E8F0; margin:0 0 24px; text-transform:uppercase; letter-spacing:0.5px;">${name}</p>

      <!-- FORMAL PARA -->
      <p style="font-size:13px; color:#94A3B8; line-height:1.9; margin:0 0 20px; text-align:justify;">
        This is to certify that your cybercrime complaint has been officially registered with the <strong style="color:#E2E8F0;">CyberShield National Cyber Intelligence Platform</strong> operated under the Ministry of Home Affairs, Government of India. Your complaint has been processed by our Zephyr 7B AI Classification Engine and assigned to the competent authority for investigation.
      </p>

      <!-- CASE DETAILS TABLE -->
      <table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 28px; border:1px solid rgba(255,255,255,0.07); border-radius:4px; overflow:hidden;">
        <tr style="background:#1E293B;">
          <td colspan="2" style="padding:10px 16px; font-size:10px; font-family:'Courier New',monospace; color:#64748B; letter-spacing:2px; text-transform:uppercase; border-bottom:1px solid rgba(255,255,255,0.06);">
            &#9632; Case Details
          </td>
        </tr>
        <tr style="background:#0F172A;">
          <td style="padding:10px 16px; font-size:12px; color:#64748B; font-family:'Courier New',monospace; width:40%; border-bottom:1px solid rgba(255,255,255,0.04);">Reference No.</td>
          <td style="padding:10px 16px; font-size:12px; color:#00D4FF; font-family:'Courier New',monospace; font-weight:700; border-bottom:1px solid rgba(255,255,255,0.04);">${ref_no}</td>
        </tr>
        <tr style="background:#0D1526;">
          <td style="padding:10px 16px; font-size:12px; color:#64748B; font-family:'Courier New',monospace; border-bottom:1px solid rgba(255,255,255,0.04);">Crime Category</td>
          <td style="padding:10px 16px; font-size:12px; color:#E2E8F0; font-family:Arial,sans-serif; font-weight:600; border-bottom:1px solid rgba(255,255,255,0.04);">${categories.join(' / ')}</td>
        </tr>
        <tr style="background:#0F172A;">
          <td style="padding:10px 16px; font-size:12px; color:#64748B; font-family:'Courier New',monospace; border-bottom:1px solid rgba(255,255,255,0.04);">Severity Level</td>
          <td style="padding:10px 16px; border-bottom:1px solid rgba(255,255,255,0.04);">
            <span style="background:${sev.bg}; color:${sev.badge}; padding:3px 10px; border-radius:3px; font-size:11px; font-weight:700; font-family:'Courier New',monospace; letter-spacing:1px;">${severity}</span>
          </td>
        </tr>
        <tr style="background:#0D1526;">
          <td style="padding:10px 16px; font-size:12px; color:#64748B; font-family:'Courier New',monospace;">Date & Time Filed</td>
          <td style="padding:10px 16px; font-size:12px; color:#E2E8F0; font-family:'Courier New',monospace;">${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', day:'2-digit', month:'long', year:'numeric', hour:'2-digit', minute:'2-digit', hour12:true })} IST</td>
        </tr>
      </table>

      <!-- INSTRUCTIONS HEADER -->
      <div style="background:#1E293B; border-left:3px solid #00D4FF; padding:12px 16px; margin-bottom:16px; border-radius:0 4px 4px 0;">
        <div style="font-size:10px; color:#00D4FF; font-family:'Courier New',monospace; letter-spacing:2px; text-transform:uppercase; font-weight:700;">&#9632; Mandatory Instructions for Complainant</div>
      </div>

      <!-- NUMBERED INSTRUCTIONS -->
      <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
        ${[
          ['Preserve Reference Number', `Quote <strong style="color:#00D4FF; font-family:'Courier New',monospace;">${ref_no}</strong> in all future communications with law enforcement.`],
          ['Do NOT Destroy Evidence', 'Preserve all screenshots, transaction receipts, call recordings, chat logs, and emails pertaining to this incident.'],
          ['Track Your Case Online', `Visit <a href="https://cybershield.vercel.app/track/${ref_no}" style="color:#00D4FF;">cybershield.vercel.app/track/${ref_no}</a> for real-time case status updates.`],
          ['Initiate Financial Block', 'If financial fraud has occurred, immediately contact your bank to freeze the transaction or reverse the transfer (within 24 hours significantly improves recovery chances).'],
        ].map(([title, desc], i) => `
        <tr>
          <td valign="top" style="padding:0 0 14px 0;">
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td valign="top" style="width:30px; padding-top:2px;">
                  <div style="width:22px; height:22px; background:#1E293B; border:1px solid rgba(0,212,255,0.3); border-radius:3px; text-align:center; line-height:22px; font-size:11px; font-weight:700; color:#00D4FF; font-family:'Courier New',monospace;">${i+1}</div>
                </td>
                <td style="padding-left:10px;">
                  <div style="font-size:12px; font-weight:700; color:#E2E8F0; margin-bottom:3px;">${title}</div>
                  <div style="font-size:12px; color:#94A3B8; line-height:1.7;">${desc}</div>
                </td>
              </tr>
            </table>
          </td>
        </tr>`).join('')}
      </table>

      <!-- HELPLINES -->
      <div style="background:#1E293B; border-left:3px solid #FF6B00; padding:12px 16px; margin-bottom:16px; border-radius:0 4px 4px 0;">
        <div style="font-size:10px; color:#FF6B00; font-family:'Courier New',monospace; letter-spacing:2px; text-transform:uppercase; font-weight:700;">&#9632; 24x7 National Emergency Helplines</div>
      </div>
      <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
        <tr>
          ${[['1930','Cyber Crime Cell'],['112','National Emergency'],['181','Women Helpline'],['1091','Women Safety']].map(([num, lbl]) => `
          <td align="center" style="padding:4px;">
            <div style="background:#0F172A; border:1px solid rgba(255,255,255,0.07); border-radius:4px; padding:12px 8px;">
              <div style="font-size:22px; font-weight:900; color:#00D4FF; font-family:'Courier New',monospace;">${num}</div>
              <div style="font-size:9px; color:#64748B; text-transform:uppercase; letter-spacing:1px; margin-top:4px;">${lbl}</div>
            </div>
          </td>`).join('')}
        </tr>
      </table>

      <!-- OFFICIAL SIGN-OFF -->
      <table width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid rgba(255,255,255,0.07); padding-top:20px; margin-top:8px;">
        <tr>
          <td>
            <div style="font-size:12px; color:#94A3B8;">Yours faithfully,</div>
            <div style="font-size:14px; font-weight:700; color:#E2E8F0; margin-top:8px;">System Administrator</div>
            <div style="font-size:11px; color:#64748B; font-family:'Courier New',monospace;">CyberShield AI Platform</div>
            <div style="font-size:11px; color:#475569; font-family:'Courier New',monospace;">National Cyber Crime Intelligence Cell</div>
            <div style="font-size:11px; color:#475569; font-family:'Courier New',monospace;">Ministry of Home Affairs, Government of India</div>
          </td>
          <td align="right" valign="bottom">
            <div style="font-size:9px; color:#334155; font-family:'Courier New',monospace; text-align:right; line-height:1.8;">
              DIGITALLY SIGNED<br>
              CyberShield AI System<br>
              ${new Date().toLocaleDateString('en-IN')}<br>
              &#9632;&#9632;&#9632;&#9632;&#9632;&#9632;&#9632;&#9632;
            </div>
          </td>
        </tr>
      </table>

    </td>
  </tr>

  <!-- FOOTER -->
  <tr><td>${govtFooter(ref_no)}</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`;

  await transporter.sendMail({
    from: SENDER_DISPLAY,
    replyTo: SENDER_ADDRESS,
    to,
    subject: `[Complaint Registered] E-FIR Acknowledgment — Ref: ${ref_no} | CyberShield India`,
    html
  });
}

// ── Official FIR Document Email ───────────────────────────────
export async function sendFirEmail(to, data) {
  const { ref_no, categories, severity, department, bns_sections, original_text, translated_text, name, city } = data;
  const sev = severityColor(severity);

  const bnsRows = (bns_sections || []).map((s, i) => `
    <tr style="background:${i % 2 === 0 ? '#0F172A' : '#0D1526'};">
      <td style="padding:8px 16px; font-size:11px; color:#64748B; font-family:'Courier New',monospace; width:20px; border-bottom:1px solid rgba(255,255,255,0.04);">${String(i+1).padStart(2,'0')}</td>
      <td style="padding:8px 16px; font-size:12px; color:#A78BFA; font-family:'Courier New',monospace; border-bottom:1px solid rgba(255,255,255,0.04);">${s.split(':')[0].trim()}</td>
      <td style="padding:8px 16px; font-size:12px; color:#94A3B8; border-bottom:1px solid rgba(255,255,255,0.04);">${s.includes(':') ? s.split(':')[1].trim() : ''}</td>
    </tr>`).join('');

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>First Information Report — ${ref_no}</title>
</head>
<body style="margin:0; padding:0; background:#0A0F1E; font-family:Arial,'Helvetica Neue',sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0" style="background:#0A0F1E; padding:30px 20px;">
<tr><td align="center">
<table width="680" cellpadding="0" cellspacing="0" style="background:#0D1526; border-radius:4px; overflow:hidden; border:1px solid rgba(255,255,255,0.08); box-shadow:0 0 60px rgba(0,0,0,0.6);">

  <!-- GOVERNMENT HEADER -->
  <tr><td>
    ${govtHeader('FIRST INFORMATION REPORT (E-FIR)', 'AI-Classified Crime Intelligence Document — CONFIDENTIAL')}
  </td></tr>

  <!-- CLASSIFICATION BANNER -->
  <tr>
    <td style="background:#${severity === 'Critical' ? '7f1d1d' : severity === 'High' ? '78350f' : '1e293b'}; padding:10px 40px;">
      <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td>
            <span style="font-size:10px; font-family:'Courier New',monospace; color:${sev.badge}; letter-spacing:3px; text-transform:uppercase; font-weight:700;">
              &#9632; CLASSIFICATION: ${severity.toUpperCase()} PRIORITY &nbsp;|&nbsp; RESTRICTED ACCESS
            </span>
          </td>
          <td align="right">
            <span style="font-size:10px; font-family:'Courier New',monospace; color:#475569; letter-spacing:1px;">
              FIR NO: ${ref_no}
            </span>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <!-- REF + META -->
  <tr>
    <td style="background:#1E293B; padding:20px 40px; border-bottom:1px solid rgba(255,255,255,0.06);">
      <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td>
            <div style="font-size:10px; color:#64748B; font-family:'Courier New',monospace; letter-spacing:2px; text-transform:uppercase; margin-bottom:6px;">FIR Number</div>
            <div style="font-size:30px; font-weight:900; color:#E2E8F0; font-family:'Courier New',monospace; letter-spacing:6px;">${ref_no}</div>
          </td>
          <td align="right" valign="top">
            <table cellpadding="0" cellspacing="0">
              <tr>
                <td align="right">
                  <div style="font-size:9px; color:#64748B; font-family:'Courier New',monospace; margin-bottom:4px; letter-spacing:1px; text-transform:uppercase;">Date of Registration</div>
                  <div style="font-size:11px; color:#94A3B8; font-family:'Courier New',monospace;">${new Date().toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata', day:'2-digit', month:'long', year:'numeric' })}</div>
                  <div style="margin-top:8px; font-size:9px; color:#334155; font-family:'Courier New',monospace; letter-spacing:2px;">|||||||||||||||||||||||</div>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <!-- BODY -->
  <tr>
    <td style="padding:32px 40px;">

      <!-- SECTION 1: COMPLAINANT -->
      <div style="background:#1E293B; border-left:3px solid #00D4FF; padding:10px 16px; margin-bottom:12px; border-radius:0 4px 4px 0;">
        <div style="font-size:10px; color:#00D4FF; font-family:'Courier New',monospace; letter-spacing:2px; font-weight:700; text-transform:uppercase;">&#9632; Section I — Complainant Details</div>
      </div>
      <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px; border:1px solid rgba(255,255,255,0.07); border-radius:4px; overflow:hidden;">
        ${[
          ['Name of Complainant', name],
          ['City / Jurisdiction', `${city || 'Not Specified'} Cyber Crime Cell`],
          ['Assigned Department', department],
          ['Nature of Offence', categories.join(' + ')],
        ].map(([k, v], i) => `
        <tr style="background:${i % 2 === 0 ? '#0F172A' : '#0D1526'};">
          <td style="padding:10px 16px; font-size:11px; color:#64748B; font-family:'Courier New',monospace; width:200px; border-bottom:1px solid rgba(255,255,255,0.04);">${k}</td>
          <td style="padding:10px 16px; font-size:12px; color:#E2E8F0; font-weight:600; border-bottom:1px solid rgba(255,255,255,0.04);">${v}</td>
        </tr>`).join('')}
      </table>

      <!-- SECTION 2: AI ASSESSMENT -->
      <div style="background:#1E293B; border-left:3px solid #7C3AED; padding:10px 16px; margin-bottom:12px; border-radius:0 4px 4px 0;">
        <div style="font-size:10px; color:#A78BFA; font-family:'Courier New',monospace; letter-spacing:2px; font-weight:700; text-transform:uppercase;">&#9632; Section II — AI Classification Profile (Zephyr 7B)</div>
      </div>
      <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px; border:1px solid rgba(255,255,255,0.07); border-radius:4px; overflow:hidden;">
        <tr style="background:#0F172A;">
          <td style="padding:10px 16px; font-size:11px; color:#64748B; font-family:'Courier New',monospace; width:200px; border-bottom:1px solid rgba(255,255,255,0.04);">Crime Categories</td>
          <td style="padding:10px 16px; border-bottom:1px solid rgba(255,255,255,0.04);">
            ${categories.map(c => `<span style="display:inline-block; background:rgba(0,212,255,0.1); border:1px solid rgba(0,212,255,0.25); color:#00D4FF; padding:2px 10px; border-radius:3px; font-size:11px; margin-right:6px; font-family:'Courier New',monospace;">${c}</span>`).join('')}
          </td>
        </tr>
        <tr style="background:#0D1526;">
          <td style="padding:10px 16px; font-size:11px; color:#64748B; font-family:'Courier New',monospace; border-bottom:1px solid rgba(255,255,255,0.04);">Severity Classification</td>
          <td style="padding:10px 16px; border-bottom:1px solid rgba(255,255,255,0.04);">
            <span style="background:${sev.bg}; color:${sev.badge}; padding:3px 12px; border-radius:3px; font-size:11px; font-weight:700; font-family:'Courier New',monospace; letter-spacing:1px;">&#9632; ${severity.toUpperCase()}</span>
          </td>
        </tr>
        <tr style="background:#0F172A;">
          <td style="padding:10px 16px; font-size:11px; color:#64748B; font-family:'Courier New',monospace;">Routing Authority</td>
          <td style="padding:10px 16px; font-size:12px; color:#E2E8F0; font-weight:600;">${department}</td>
        </tr>
      </table>

      <!-- SECTION 3: BNS SECTIONS -->
      <div style="background:#1E293B; border-left:3px solid #A78BFA; padding:10px 16px; margin-bottom:12px; border-radius:0 4px 4px 0;">
        <div style="font-size:10px; color:#A78BFA; font-family:'Courier New',monospace; letter-spacing:2px; font-weight:700; text-transform:uppercase;">&#9632; Section III — Applicable Legal Provisions (Bharatiya Nyaya Sanhita 2024)</div>
      </div>
      <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px; border:1px solid rgba(255,255,255,0.07); border-radius:4px; overflow:hidden;">
        <tr style="background:#1E293B;">
          <td style="padding:8px 16px; font-size:9px; color:#64748B; font-family:'Courier New',monospace; letter-spacing:2px; border-bottom:1px solid rgba(255,255,255,0.06);">#</td>
          <td style="padding:8px 16px; font-size:9px; color:#64748B; font-family:'Courier New',monospace; letter-spacing:2px; border-bottom:1px solid rgba(255,255,255,0.06);">SECTION</td>
          <td style="padding:8px 16px; font-size:9px; color:#64748B; font-family:'Courier New',monospace; letter-spacing:2px; border-bottom:1px solid rgba(255,255,255,0.06);">DESCRIPTION</td>
        </tr>
        ${bnsRows || `<tr><td colspan="3" style="padding:12px 16px; font-size:12px; color:#475569; font-style:italic;">Pending manual review by Investigating Officer.</td></tr>`}
      </table>

      <!-- SECTION 4: COMPLAINT TEXT -->
      <div style="background:#1E293B; border-left:3px solid #F59E0B; padding:10px 16px; margin-bottom:12px; border-radius:0 4px 4px 0;">
        <div style="font-size:10px; color:#F59E0B; font-family:'Courier New',monospace; letter-spacing:2px; font-weight:700; text-transform:uppercase;">&#9632; Section IV — Complainant's Original Statement</div>
      </div>
      <div style="background:#0F172A; border:1px solid rgba(255,255,255,0.07); border-left:3px solid #F59E0B; border-radius:4px; padding:20px; margin-bottom:28px; font-size:13px; color:#94A3B8; line-height:1.9; font-family:Georgia,serif;">
        "${original_text}"
      </div>

      ${translated_text && translated_text !== original_text ? `
      <!-- SECTION 4B: TRANSLATED -->
      <div style="background:#1E293B; border-left:3px solid #22C55E; padding:10px 16px; margin-bottom:12px; border-radius:0 4px 4px 0;">
        <div style="font-size:10px; color:#22C55E; font-family:'Courier New',monospace; letter-spacing:2px; font-weight:700; text-transform:uppercase;">&#9632; Section IV-B — Standardized English Translation (Zephyr AI)</div>
      </div>
      <div style="background:#0F172A; border:1px solid rgba(255,255,255,0.07); border-left:3px solid #22C55E; border-radius:4px; padding:20px; margin-bottom:28px; font-size:13px; color:#94A3B8; line-height:1.9; font-family:Georgia,serif;">
        "${translated_text}"
      </div>` : ''}

      <!-- SECTION 5: WHAT TO DO NOW -->
      <div style="background:#1E293B; border-left:3px solid #EF4444; padding:10px 16px; margin-bottom:12px; border-radius:0 4px 4px 0;">
        <div style="font-size:10px; color:#EF4444; font-family:'Courier New',monospace; letter-spacing:2px; font-weight:700; text-transform:uppercase;">&#9632; Section V — Immediate Action Required</div>
      </div>
      ${severity === 'Critical' || severity === 'High' ? `
      <div style="background:#7f1d1d; border:1px solid rgba(239,68,68,0.3); border-radius:4px; padding:14px 18px; margin-bottom:16px; font-size:12px; color:#FCA5A5; font-family:'Courier New',monospace; letter-spacing:0.5px;">
        &#9888; URGENT: If you are in immediate physical danger, call <strong>112</strong> now. For financial cyber fraud, call <strong>1930</strong> immediately to initiate bank transaction reversal.
      </div>` : ''}
      <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
        ${[
          'Do NOT delete any evidence — screenshots, messages, transaction IDs, call recordings',
          'Block your UPI / bank account immediately if financial fraud occurred',
          'Do not contact or engage with the suspect — it may compromise the investigation',
          `Track your case status at: cybershield.vercel.app/track/${ref_no}`,
          'An investigating officer from ' + department + ' will contact you within the prescribed time',
        ].map((step, i) => `
        <tr>
          <td valign="top" style="padding:0 0 10px 0;">
            <table cellpadding="0" cellspacing="0">
              <tr>
                <td valign="top" style="width:28px;">
                  <span style="display:inline-block; width:20px; height:20px; background:#1E293B; border:1px solid rgba(239,68,68,0.3); border-radius:3px; text-align:center; line-height:20px; font-size:10px; font-weight:700; color:#EF4444; font-family:'Courier New',monospace;">${i+1}</span>
                </td>
                <td style="padding-left:10px; font-size:12px; color:#94A3B8; line-height:1.7;">${step}</td>
              </tr>
            </table>
          </td>
        </tr>`).join('')}
      </table>

      <!-- OFFICIAL SIGN-OFF -->
      <table width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid rgba(255,255,255,0.07); padding-top:24px; margin-top:8px;">
        <tr>
          <td>
            <div style="font-size:12px; color:#94A3B8;">Registered and issued by authority of:</div>
            <div style="font-size:14px; font-weight:700; color:#E2E8F0; margin-top:10px;">Inspector / System Controller</div>
            <div style="font-size:11px; color:#64748B; font-family:'Courier New',monospace;">CyberShield AI — National Cyber Crime Intelligence Cell</div>
            <div style="font-size:11px; color:#475569; font-family:'Courier New',monospace;">Ministry of Home Affairs, Government of India</div>
            <div style="font-size:11px; color:#475569; font-family:'Courier New',monospace; margin-top:4px;">Helpline: 1930 (Cyber Crime) | Emergency: 112</div>
          </td>
          <td align="right" valign="bottom">
            <div style="font-size:9px; color:#334155; font-family:'Courier New',monospace; text-align:right; line-height:2;">
              DIGITALLY AUTHENTICATED<br>
              ZEPHYR 7B AI ENGINE<br>
              ${new Date().toLocaleDateString('en-IN')}<br>
              &#9632;&#9632;&#9632;&#9632;&#9632;&#9632;&#9632;&#9632;
            </div>
          </td>
        </tr>
      </table>

    </td>
  </tr>

  <!-- FOOTER -->
  <tr><td>${govtFooter(ref_no)}</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`;

  await transporter.sendMail({
    from: SENDER_DISPLAY,
    replyTo: SENDER_ADDRESS,
    to,
    subject: `[OFFICIAL E-FIR] ${severity} Priority — FIR No. ${ref_no} | CyberShield National Cyber Cell`,
    html
  });
}

// ── OTP email ─────────────────────────────────────────────────
export async function sendOtpEmail(to, otp) {
  const html = `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0; padding:0; background:#0A0F1E; font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#0A0F1E; padding:30px 20px;">
<tr><td align="center">
<table width="500" cellpadding="0" cellspacing="0" style="background:#0D1526; border-radius:4px; overflow:hidden; border:1px solid rgba(255,255,255,0.08);">
  <tr>
    <td>
      <table width="100%" cellpadding="0" cellspacing="0" style="background:#0F172A; border-bottom:3px solid #FF6B00;">
        <tr><td style="height:4px; background:#FF6B00;"></td></tr>
        <tr><td style="height:4px; background:#FFFFFF;"></td></tr>
        <tr><td style="height:4px; background:#138808;"></td></tr>
      </table>
    </td>
  </tr>
  <tr>
    <td style="padding:30px 40px; text-align:center;">
      <div style="font-size:11px; color:#64748B; font-family:'Courier New',monospace; letter-spacing:2px; margin-bottom:8px;">GOVERNMENT OF INDIA — CYBERSHIELD INDIA</div>
      <div style="font-size:18px; font-weight:700; color:#E2E8F0; font-family:Georgia,serif;">Secure Login Verification</div>
    </td>
  </tr>
  <tr>
    <td style="padding:0 40px 30px; text-align:center;">
      <div style="font-size:12px; color:#94A3B8; margin-bottom:20px; line-height:1.7;">Your One-Time Password (OTP) for secure access to CyberShield Portal:</div>
      <div style="font-size:40px; font-weight:900; color:#00D4FF; font-family:'Courier New',monospace; letter-spacing:10px; background:#0F172A; border:1px dashed rgba(0,212,255,0.3); border-radius:4px; padding:16px; margin:0 auto 16px;">${otp}</div>
      <div style="font-size:11px; color:#64748B; font-family:'Courier New',monospace; letter-spacing:1px;">VALID FOR 10 MINUTES &nbsp;|&nbsp; DO NOT SHARE WITH ANYONE</div>
    </td>
  </tr>
  <tr>
    <td style="background:#0F172A; padding:16px 40px; border-top:1px solid rgba(255,255,255,0.06); text-align:center;">
      <div style="font-size:10px; color:#334155; font-family:'Courier New',monospace;">CyberShield India — National Cyber Crime Intelligence Platform — DO NOT REPLY</div>
    </td>
  </tr>
</table>
</td></tr>
</table>
</body>
</html>`;

  await transporter.sendMail({
    from: SENDER_DISPLAY,
    replyTo: SENDER_ADDRESS,
    to,
    subject: `[CyberShield Security] Your OTP: ${otp} — Do Not Share`,
    html
  });
}

